### ISSUE TITLE
chore: Build an environment

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/portfolio#1]
### Context

環境構築を行う

### TODO

- [ ] chore(ci): GitHub Issue / PR templates
- [ ] chore(ci): Renovate bot
- [ ] chore: build an ESLint
