### ISSUE TITLE
chore: add `Nuxt Scripts`

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/portfolio#18]
### Context

- `Nuxt Scripts`を追加しGoogle Analytics連携を行いたい
- 合わせて以下のモジュールも追加する
  - `Nuxt OG Image`
  - `Nuxt SEO`
  - `Nuxt Simple Robots`

#### Note

- 対応膨れそうだったら子イシューに切り出す

### TODO

- [ ] add `Nuxt Scripts`
- [ ] chore: add `Nuxt OG Image`
- [ ] chore: add `Nuxt SEO`
- [ ] chore: add `Nuxt Simple Robots`
